# Generated by Django 2.1.5 on 2019-01-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exer_190131', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
