# Generated by Django 2.1.5 on 2019-01-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exer_190131', '0002_movie_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='picture1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.IntegerField(),
        ),
    ]
